### PR TITLE
feat: started collection page layout

### PR DESCRIPTION
**Pull request by YohanTz**

### CODE REVIEW

**Review by kwiss — COMMENTED** [review]
globally it look good i think the naming of the main file is a bit weird (collection-items-activity) but i guess it will change after the integration of the fetch

**Comment by kwiss** [comment]
maybe we should have both mode with & without banner because we don't have one it look strange (to be check with nolo)

**Comment by kwiss** [comment]
icons are a bit big

**Comment by YohanTz** [comment]
> globally it look good i think the naming of the main file is a bit weird (collection-items-activity) but i guess it will change after the integration of the fetch

Yes I'm not really satisfied with it too, Any idea? Because it contains both items and activity tabs components

**Comment by YohanTz** [comment]
> maybe we should have both mode with & without banner because we don't have one it look strange (to be check with nolo)

Mmh maybe yes, or a default banner

**Comment by YohanTz** [comment]
> icons are a bit big

On the grid / list view toggle?

**Comment by kwiss** [comment]
> > icons are a bit big
> 
> On the grid / list view toggle?

yes

**Review by kwiss — APPROVED** [review]

**Pull request merged**
